public enum ItemType
{
    // Hats
    Hat_None = 0,
    Hat_Crown = 1,
    Hat_CatEars = 2,
    Hat_BucketHat = 3,
    Hat_CowboyHat = 4,
    Hat_TopHat = 5,
    Hat_Tiara = 6,
    Hat_Bow = 7,
    Hat_Mushroom = 8,
    Hat_BugOfLove = 9,
    Hat_Plumbob = 10,
    Hat_FishingCap = 11,
    Hat_Detective = 12,
    Hat_Infested = 13,
    Hat_Flower = 14,
    Hat_Wooden = 15,
    Hat_Crystalized = 16,
    Hat_Moss = 17,
    Hat_Weeded = 18,
    Hat_Oily = 19,
    Hat_Polluted = 20,

    // Faces
    Face_None = 100,
    Face_Moustache = 101,
    Face_Glasses_Scientist = 102,
    Face_Glasses_Round = 103,
    Face_Monocle = 104,
    Face_Septum = 105,
    Face_Cigarette = 106,

    // Colors
    Color_Default = 200,
    Color_Green = 201,
    Color_Red = 202,
    Color_Blue = 203,
    Color_Yellow = 204,
    Color_Pink = 205,
    Color_Brown = 206,
    Color_Gray = 207,
    Color_White = 208,
    Color_Black = 209,
    Color_Cyan = 210,

    // Aura
    Particles_None = 300,
    Particles_Debug = 301,
    Particles_Hearts = 302,
    Particles_Bubbles = 303,
    Particles_Eyes = 304,
    Particles_Water = 305,
    Particles_Leaves = 306,
    Particles_Money = 307,
    Particles_Stars = 308,
    Particles_Sandy = 309,
}
